### ISSUE TITLE
兄弟可以留个QQ吗

### ISSUE THREAD

**Issue by whj33** [50kg/BilibiliProjectDemo#2]
问个问题   我QQ200863405

**Comment by 50kg** [comment]
sanji2020微信发自我的华为手机-------- 原始邮件 --------主题：[50kg/BilibiliProjectDemo] 兄弟可以留个QQ吗 (#2)发件人：whj33 收件人：50kg/BilibiliProjectDemo 抄送：Subscribed 问个问题   我QQ200863405

**Comment by Chexian1** [comment]
为什么我的打开后没有数据

**Comment by 50kg** [comment]
> 为什么我的打开后没有数据

可能b站接口更改了，此项目不维护了
